version: '3.5'

services:
  ml-frontend:
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    ports:
      - 3000:3000

  ml-backend:
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    depends_on:
      - ml-training

  ml-training:
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    volumes:
      - data:/src/data
      - imgs:/src/imgs
      - model:/src/model

volumes:
  imgs:
  model:
  data:
